# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 08124cbc7bd3cbc13bc36ae0617fbb5677c38a150a7034afe35cad88369f0376fc0248787c6846d34b8e0b09cebfceb74aa32f548f7971486af5558b0749b43f

test:
  secret_key_base: 8b09c81d8726ffd5ba753561afd33c54ac17255e603d7fd3730e9f3756c99bc7a11005cbed7dfb45d67d7b747c1c0bc81dc486084d2582e03472dc8fd2acc357

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
