# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c89205a18ae038181b4b00da3cbdd9da30466b1ce0ac655aa785e9d27ba2cad76247c02a975b74938f490c3bcbf41dfd9c4957705f38bc39c468dd3386888f63

test:
  secret_key_base: 9566e87ad1327c6eb0fe4aff396614ad70d641c9b5a88f187ed26438db5989ad41df381e213b78d257f6ed0d8dc59e3bc4b1f6a85411c9fa310029b400d9d568

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
